SELECT (SELECT LD.PROSPECTCODE
          FROM QC_LOS.QT_LOANDETAIL LD
         WHERE LD.PROSPECTID = DPC.PROSPECT_ID) AS PROSPECTCODE,
       DPC.PROSPECT_ID,
       DPC.DISBURSAL_ID,
       DPC.CLR_DATE,
       DPC.CLR_AMT,
       DPC.MAKER_ID,
       (SELECT AU.USERFNAME || ' ' || NVL(AU.USERMNAME, '') || ' ' ||
               AU.USERLNAME
          FROM QC_USER_AUTH.QM_USER AU
         WHERE AU.USERID = DPC.MAKER_ID) AS MAKER_NAME,
       DPC.MAKER_DATE,
       DPC.AUTH_ID,
       (SELECT AU.USERFNAME || ' ' || NVL(AU.USERMNAME, '') || ' ' ||
               AU.USERLNAME
          FROM QC_USER_AUTH.QM_USER AU
         WHERE AU.USERID = DPC.AUTH_ID) AS AUTHOR_NAME,
       DPC.AUTH_DATE,
       CASE
         WHEN DPC.AUTH_STATUS = 'P' THEN
          'MAKER/AUTHOR PENDING'
         ELSE
          'MAKER/AUTHOR COMPELETD'
       END AS STATUS
  FROM QC_LOS.QT_DISB_PAYMENT_CLEARANCE DPC;