DECLARE
  CURSOR c_prospect IS
    SELECT PROSPECTID, PROSPECTCODE
      FROM qc_los.QT_LOANDETAIL
     WHERE PROSPECTCODE IN ('HNSK25000083276', 'HNSK25000082563',
            'HNSK25000083314', 'HNSK25000087392');

BEGIN
  FOR rec IN c_prospect LOOP
  
    UPDATE QC_LOS.QT_LOANDETAIL
       SET LOANSUBSTATUSID = 1000000004
     WHERE PROSPECTCODE = rec.PROSPECTCODE;
	 
	 
	 DELETE FROM QC_LMS.QT_LOANCHARGE LC
     WHERE LC.PROSPECT_ID = rec.PROSPECTID
       AND LC.CHARGE_ID IN (SELECT CHARGE_ID
                              FROM QC_LMS.QT_LOANCHARGE
                             WHERE PROSPECT_ID = rec.PROSPECTID
                               AND STATUS = 'A')
       AND LC.LOANCHARGE_ID IN (SELECT LOANCHARGE_ID
                                  FROM QC_LMS.QT_LOANCHARGE
                                 WHERE PROSPECT_ID = rec.PROSPECTID
                                   AND STATUS = 'A');
  
    UPDATE QC_LMS.QT_LOANCHARGE
       SET STATUS = 'A'
     WHERE PROSPECT_ID = rec.PROSPECTID
       AND STATUS = 'X';
  
    UPDATE QC_LMS.QT_LOANCHARGE
       SET CHARGE_STATUS = '0'
     WHERE PROSPECT_ID = rec.PROSPECTID
       AND CHARGE_BAL_AMOUNT > 0;
  
   
    UPDATE QC_LMS.QT_LOAN_CHARGE_TRANS_DTL
       SET AUTH_STATUS = 'A'
     WHERE LOANCHARGE_ID IN
           (SELECT LOANCHARGE_ID
              FROM QC_LMS.QT_LOANCHARGE
             WHERE PROSPECT_ID = rec.PROSPECTID);
  
    DELETE FROM QC_ACCOUNTING.QT_ACCOUNTING
     WHERE PROSPECT_ID = rec.PROSPECTID
       AND EVENT_NAME LIKE '%REVERSAL%';
  
    DELETE FROM QC_ACCOUNTING.QT_ACCOUNTING_DTL
     WHERE PROSPECT_ID = rec.PROSPECTID
       AND EVENT_NAME LIKE '%REVERSAL%';
  
    DELETE FROM QC_LOS.QT_CANCEL_LOAN_DISBURSAL
     WHERE PROSPECT_ID = rec.PROSPECTID;
  
  END LOOP;

  COMMIT;
END;
